/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommitteeSolution,
  SolverOptions,
} from '../models/index';
import {
    CommitteeSolutionFromJSON,
    CommitteeSolutionToJSON,
    SolverOptionsFromJSON,
    SolverOptionsToJSON,
} from '../models/index';

export interface ApiCommitteeSolutionIdGetRequest {
    id: string;
}

export interface ApiCommitteeSolutionSolvePostRequest {
    solverOptions: SolverOptions;
}

export interface ApiCommitteeSolutionStopSolvingIdGetRequest {
    id: string;
}

/**
 * 
 */
export class CommitteeSolutionResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiCommitteeSolutionIdGet without sending the request
     */
    async apiCommitteeSolutionIdGetRequestOpts(requestParameters: ApiCommitteeSolutionIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCommitteeSolutionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/committeeSolution/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Solution
     */
    async apiCommitteeSolutionIdGetRaw(requestParameters: ApiCommitteeSolutionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommitteeSolution>> {
        const requestOptions = await this.apiCommitteeSolutionIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommitteeSolutionFromJSON(jsonValue));
    }

    /**
     * Get Solution
     */
    async apiCommitteeSolutionIdGet(requestParameters: ApiCommitteeSolutionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommitteeSolution> {
        const response = await this.apiCommitteeSolutionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCommitteeSolutionSolvePost without sending the request
     */
    async apiCommitteeSolutionSolvePostRequestOpts(requestParameters: ApiCommitteeSolutionSolvePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['solverOptions'] == null) {
            throw new runtime.RequiredError(
                'solverOptions',
                'Required parameter "solverOptions" was null or undefined when calling apiCommitteeSolutionSolvePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/committeeSolution/solve`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SolverOptionsToJSON(requestParameters['solverOptions']),
        };
    }

    /**
     * Solve
     */
    async apiCommitteeSolutionSolvePostRaw(requestParameters: ApiCommitteeSolutionSolvePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommitteeSolution>> {
        const requestOptions = await this.apiCommitteeSolutionSolvePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommitteeSolutionFromJSON(jsonValue));
    }

    /**
     * Solve
     */
    async apiCommitteeSolutionSolvePost(requestParameters: ApiCommitteeSolutionSolvePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommitteeSolution> {
        const response = await this.apiCommitteeSolutionSolvePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCommitteeSolutionStopSolvingIdGet without sending the request
     */
    async apiCommitteeSolutionStopSolvingIdGetRequestOpts(requestParameters: ApiCommitteeSolutionStopSolvingIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCommitteeSolutionStopSolvingIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/committeeSolution/stopSolving/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stop Solving
     */
    async apiCommitteeSolutionStopSolvingIdGetRaw(requestParameters: ApiCommitteeSolutionStopSolvingIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiCommitteeSolutionStopSolvingIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stop Solving
     */
    async apiCommitteeSolutionStopSolvingIdGet(requestParameters: ApiCommitteeSolutionStopSolvingIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiCommitteeSolutionStopSolvingIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
