/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitteeAssignment } from './CommitteeAssignment';
import {
    CommitteeAssignmentFromJSON,
    CommitteeAssignmentFromJSONTyped,
    CommitteeAssignmentToJSON,
    CommitteeAssignmentToJSONTyped,
} from './CommitteeAssignment';
import type { SolverStatus } from './SolverStatus';
import {
    SolverStatusFromJSON,
    SolverStatusFromJSONTyped,
    SolverStatusToJSON,
    SolverStatusToJSONTyped,
} from './SolverStatus';
import type { Settings } from './Settings';
import {
    SettingsFromJSON,
    SettingsFromJSONTyped,
    SettingsToJSON,
    SettingsToJSONTyped,
} from './Settings';
import type { HardMediumSoftScore } from './HardMediumSoftScore';
import {
    HardMediumSoftScoreFromJSON,
    HardMediumSoftScoreFromJSONTyped,
    HardMediumSoftScoreToJSON,
    HardMediumSoftScoreToJSONTyped,
} from './HardMediumSoftScore';

/**
 * 
 * @export
 * @interface CommitteeSolution
 */
export interface CommitteeSolution {
    /**
     * 
     * @type {string}
     * @memberof CommitteeSolution
     */
    id?: string;
    /**
     * 
     * @type {Settings}
     * @memberof CommitteeSolution
     */
    settings?: Settings;
    /**
     * 
     * @type {Array<CommitteeAssignment>}
     * @memberof CommitteeSolution
     */
    committeeAssignments?: Array<CommitteeAssignment>;
    /**
     * 
     * @type {HardMediumSoftScore}
     * @memberof CommitteeSolution
     */
    score?: HardMediumSoftScore;
    /**
     * 
     * @type {string}
     * @memberof CommitteeSolution
     */
    scoreExplanation?: string;
    /**
     * 
     * @type {SolverStatus}
     * @memberof CommitteeSolution
     */
    solverStatus?: SolverStatus;
}



/**
 * Check if a given object implements the CommitteeSolution interface.
 */
export function instanceOfCommitteeSolution(value: object): value is CommitteeSolution {
    return true;
}

export function CommitteeSolutionFromJSON(json: any): CommitteeSolution {
    return CommitteeSolutionFromJSONTyped(json, false);
}

export function CommitteeSolutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitteeSolution {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'settings': json['settings'] == null ? undefined : SettingsFromJSON(json['settings']),
        'committeeAssignments': json['committeeAssignments'] == null ? undefined : ((json['committeeAssignments'] as Array<any>).map(CommitteeAssignmentFromJSON)),
        'score': json['score'] == null ? undefined : HardMediumSoftScoreFromJSON(json['score']),
        'scoreExplanation': json['scoreExplanation'] == null ? undefined : json['scoreExplanation'],
        'solverStatus': json['solverStatus'] == null ? undefined : SolverStatusFromJSON(json['solverStatus']),
    };
}

export function CommitteeSolutionToJSON(json: any): CommitteeSolution {
    return CommitteeSolutionToJSONTyped(json, false);
}

export function CommitteeSolutionToJSONTyped(value?: CommitteeSolution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'settings': SettingsToJSON(value['settings']),
        'committeeAssignments': value['committeeAssignments'] == null ? undefined : ((value['committeeAssignments'] as Array<any>).map(CommitteeAssignmentToJSON)),
        'score': HardMediumSoftScoreToJSON(value['score']),
        'scoreExplanation': value['scoreExplanation'],
        'solverStatus': SolverStatusToJSON(value['solverStatus']),
    };
}

