/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Committee } from './Committee';
import {
    CommitteeFromJSON,
    CommitteeFromJSONTyped,
    CommitteeToJSON,
    CommitteeToJSONTyped,
} from './Committee';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
    PersonToJSONTyped,
} from './Person';

/**
 * 
 * @export
 * @interface CommitteeAssignment
 */
export interface CommitteeAssignment {
    /**
     * 
     * @type {number}
     * @memberof CommitteeAssignment
     */
    id?: number;
    /**
     * 
     * @type {Person}
     * @memberof CommitteeAssignment
     */
    assignedPerson?: Person;
    /**
     * 
     * @type {Committee}
     * @memberof CommitteeAssignment
     */
    committee?: Committee;
}

/**
 * Check if a given object implements the CommitteeAssignment interface.
 */
export function instanceOfCommitteeAssignment(value: object): value is CommitteeAssignment {
    return true;
}

export function CommitteeAssignmentFromJSON(json: any): CommitteeAssignment {
    return CommitteeAssignmentFromJSONTyped(json, false);
}

export function CommitteeAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitteeAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'assignedPerson': json['assignedPerson'] == null ? undefined : PersonFromJSON(json['assignedPerson']),
        'committee': json['committee'] == null ? undefined : CommitteeFromJSON(json['committee']),
    };
}

export function CommitteeAssignmentToJSON(json: any): CommitteeAssignment {
    return CommitteeAssignmentToJSONTyped(json, false);
}

export function CommitteeAssignmentToJSONTyped(value?: CommitteeAssignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'assignedPerson': PersonToJSON(value['assignedPerson']),
        'committee': CommitteeToJSON(value['committee']),
    };
}

