/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HardMediumSoftScore
 */
export interface HardMediumSoftScore {
    /**
     * 
     * @type {number}
     * @memberof HardMediumSoftScore
     * @deprecated
     */
    initScore?: number;
    /**
     * 
     * @type {boolean}
     * @memberof HardMediumSoftScore
     */
    zero?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HardMediumSoftScore
     * @deprecated
     */
    solutionInitialized?: boolean;
    /**
     * 
     * @type {number}
     * @memberof HardMediumSoftScore
     */
    hardScore?: number;
    /**
     * 
     * @type {number}
     * @memberof HardMediumSoftScore
     */
    mediumScore?: number;
    /**
     * 
     * @type {number}
     * @memberof HardMediumSoftScore
     */
    softScore?: number;
    /**
     * 
     * @type {boolean}
     * @memberof HardMediumSoftScore
     */
    feasible?: boolean;
}

/**
 * Check if a given object implements the HardMediumSoftScore interface.
 */
export function instanceOfHardMediumSoftScore(value: object): value is HardMediumSoftScore {
    return true;
}

export function HardMediumSoftScoreFromJSON(json: any): HardMediumSoftScore {
    return HardMediumSoftScoreFromJSONTyped(json, false);
}

export function HardMediumSoftScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): HardMediumSoftScore {
    if (json == null) {
        return json;
    }
    return {
        
        'initScore': json['initScore'] == null ? undefined : json['initScore'],
        'zero': json['zero'] == null ? undefined : json['zero'],
        'solutionInitialized': json['solutionInitialized'] == null ? undefined : json['solutionInitialized'],
        'hardScore': json['hardScore'] == null ? undefined : json['hardScore'],
        'mediumScore': json['mediumScore'] == null ? undefined : json['mediumScore'],
        'softScore': json['softScore'] == null ? undefined : json['softScore'],
        'feasible': json['feasible'] == null ? undefined : json['feasible'],
    };
}

export function HardMediumSoftScoreToJSON(json: any): HardMediumSoftScore {
    return HardMediumSoftScoreToJSONTyped(json, false);
}

export function HardMediumSoftScoreToJSONTyped(value?: HardMediumSoftScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'initScore': value['initScore'],
        'zero': value['zero'],
        'solutionInitialized': value['solutionInitialized'],
        'hardScore': value['hardScore'],
        'mediumScore': value['mediumScore'],
        'softScore': value['softScore'],
        'feasible': value['feasible'],
    };
}

