/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Skill } from './Skill';
import {
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
    SkillToJSONTyped,
} from './Skill';
import type { PersonType } from './PersonType';
import {
    PersonTypeFromJSON,
    PersonTypeFromJSONTyped,
    PersonTypeToJSON,
    PersonTypeToJSONTyped,
} from './PersonType';
import type { TimeSlot } from './TimeSlot';
import {
    TimeSlotFromJSON,
    TimeSlotFromJSONTyped,
    TimeSlotToJSON,
    TimeSlotToJSONTyped,
} from './TimeSlot';
import type { Settings } from './Settings';
import {
    SettingsFromJSON,
    SettingsFromJSONTyped,
    SettingsToJSON,
    SettingsToJSONTyped,
} from './Settings';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    name?: string;
    /**
     * 
     * @type {PersonType}
     * @memberof Person
     */
    personType?: PersonType;
    /**
     * 
     * @type {Array<Skill>}
     * @memberof Person
     */
    skills?: Array<Skill>;
    /**
     * 
     * @type {Location}
     * @memberof Person
     */
    location?: Location;
    /**
     * 
     * @type {Array<TimeSlot>}
     * @memberof Person
     */
    availability?: Array<TimeSlot>;
    /**
     * 
     * @type {Array<Skill>}
     * @memberof Person
     */
    requiredSkills?: Array<Skill>;
    /**
     * 
     * @type {boolean}
     * @memberof Person
     */
    needsEvaluation?: boolean;
    /**
     * 
     * @type {Array<Person>}
     * @memberof Person
     */
    vetoes?: Array<Person>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof Person
     */
    hasAlreadyInspected?: Array<Array<string>>;
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    maxNumberOfInspections?: number;
    /**
     * 
     * @type {Settings}
     * @memberof Person
     */
    settings?: Settings;
}

/**
 * Check if a given object implements the Person interface.
 */
export function instanceOfPerson(value: object): value is Person {
    return true;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'personType': json['personType'] == null ? undefined : PersonTypeFromJSON(json['personType']),
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(SkillFromJSON)),
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'availability': json['availability'] == null ? undefined : ((json['availability'] as Array<any>).map(TimeSlotFromJSON)),
        'requiredSkills': json['requiredSkills'] == null ? undefined : ((json['requiredSkills'] as Array<any>).map(SkillFromJSON)),
        'needsEvaluation': json['needsEvaluation'] == null ? undefined : json['needsEvaluation'],
        'vetoes': json['vetoes'] == null ? undefined : ((json['vetoes'] as Array<any>).map(PersonFromJSON)),
        'hasAlreadyInspected': json['hasAlreadyInspected'] == null ? undefined : json['hasAlreadyInspected'],
        'maxNumberOfInspections': json['maxNumberOfInspections'] == null ? undefined : json['maxNumberOfInspections'],
        'settings': json['settings'] == null ? undefined : SettingsFromJSON(json['settings']),
    };
}

export function PersonToJSON(json: any): Person {
    return PersonToJSONTyped(json, false);
}

export function PersonToJSONTyped(value?: Person | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'personType': PersonTypeToJSON(value['personType']),
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(SkillToJSON)),
        'location': LocationToJSON(value['location']),
        'availability': value['availability'] == null ? undefined : ((value['availability'] as Array<any>).map(TimeSlotToJSON)),
        'requiredSkills': value['requiredSkills'] == null ? undefined : ((value['requiredSkills'] as Array<any>).map(SkillToJSON)),
        'needsEvaluation': value['needsEvaluation'],
        'vetoes': value['vetoes'] == null ? undefined : ((value['vetoes'] as Array<any>).map(PersonToJSON)),
        'hasAlreadyInspected': value['hasAlreadyInspected'],
        'maxNumberOfInspections': value['maxNumberOfInspections'],
        'settings': SettingsToJSON(value['settings']),
    };
}

