/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DistanceMatrix } from './DistanceMatrix';
import {
    DistanceMatrixFromJSON,
    DistanceMatrixFromJSONTyped,
    DistanceMatrixToJSON,
    DistanceMatrixToJSONTyped,
} from './DistanceMatrix';
import type { Range } from './Range';
import {
    RangeFromJSON,
    RangeFromJSONTyped,
    RangeToJSON,
    RangeToJSONTyped,
} from './Range';

/**
 * 
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    nbProParticipants?: Range;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    numberOfAssignmentsForAProfessional?: Range;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    nbNonProParticipants?: Range;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    numberOfAssignmentsForANonProfessional?: Range;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    nbExternalParticipants?: Range;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    numberOfAssignmentsForAnExternal?: Range;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    nbRotationsToReinspect?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    nbInspectorsFollowingUp?: number;
    /**
     * 
     * @type {DistanceMatrix}
     * @memberof Settings
     */
    distanceMatrix?: DistanceMatrix;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    travellingDistanceRange?: Range;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    useAvailability?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    shuffleParticipants?: boolean;
    /**
     * 
     * @type {Range}
     * @memberof Settings
     */
    committeeMeetingSize?: Range;
}

/**
 * Check if a given object implements the Settings interface.
 */
export function instanceOfSettings(value: object): value is Settings {
    return true;
}

export function SettingsFromJSON(json: any): Settings {
    return SettingsFromJSONTyped(json, false);
}

export function SettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Settings {
    if (json == null) {
        return json;
    }
    return {
        
        'nbProParticipants': json['nbProParticipants'] == null ? undefined : RangeFromJSON(json['nbProParticipants']),
        'numberOfAssignmentsForAProfessional': json['numberOfAssignmentsForAProfessional'] == null ? undefined : RangeFromJSON(json['numberOfAssignmentsForAProfessional']),
        'nbNonProParticipants': json['nbNonProParticipants'] == null ? undefined : RangeFromJSON(json['nbNonProParticipants']),
        'numberOfAssignmentsForANonProfessional': json['numberOfAssignmentsForANonProfessional'] == null ? undefined : RangeFromJSON(json['numberOfAssignmentsForANonProfessional']),
        'nbExternalParticipants': json['nbExternalParticipants'] == null ? undefined : RangeFromJSON(json['nbExternalParticipants']),
        'numberOfAssignmentsForAnExternal': json['numberOfAssignmentsForAnExternal'] == null ? undefined : RangeFromJSON(json['numberOfAssignmentsForAnExternal']),
        'nbRotationsToReinspect': json['nbRotationsToReinspect'] == null ? undefined : json['nbRotationsToReinspect'],
        'nbInspectorsFollowingUp': json['nbInspectorsFollowingUp'] == null ? undefined : json['nbInspectorsFollowingUp'],
        'distanceMatrix': json['distanceMatrix'] == null ? undefined : DistanceMatrixFromJSON(json['distanceMatrix']),
        'travellingDistanceRange': json['travellingDistanceRange'] == null ? undefined : RangeFromJSON(json['travellingDistanceRange']),
        'useAvailability': json['useAvailability'] == null ? undefined : json['useAvailability'],
        'shuffleParticipants': json['shuffleParticipants'] == null ? undefined : json['shuffleParticipants'],
        'committeeMeetingSize': json['committeeMeetingSize'] == null ? undefined : RangeFromJSON(json['committeeMeetingSize']),
    };
}

export function SettingsToJSON(json: any): Settings {
    return SettingsToJSONTyped(json, false);
}

export function SettingsToJSONTyped(value?: Settings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nbProParticipants': RangeToJSON(value['nbProParticipants']),
        'numberOfAssignmentsForAProfessional': RangeToJSON(value['numberOfAssignmentsForAProfessional']),
        'nbNonProParticipants': RangeToJSON(value['nbNonProParticipants']),
        'numberOfAssignmentsForANonProfessional': RangeToJSON(value['numberOfAssignmentsForANonProfessional']),
        'nbExternalParticipants': RangeToJSON(value['nbExternalParticipants']),
        'numberOfAssignmentsForAnExternal': RangeToJSON(value['numberOfAssignmentsForAnExternal']),
        'nbRotationsToReinspect': value['nbRotationsToReinspect'],
        'nbInspectorsFollowingUp': value['nbInspectorsFollowingUp'],
        'distanceMatrix': DistanceMatrixToJSON(value['distanceMatrix']),
        'travellingDistanceRange': RangeToJSON(value['travellingDistanceRange']),
        'useAvailability': value['useAvailability'],
        'shuffleParticipants': value['shuffleParticipants'],
        'committeeMeetingSize': RangeToJSON(value['committeeMeetingSize']),
    };
}

