/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SolverStatus = {
    SolvingScheduled: 'SOLVING_SCHEDULED',
    SolvingActive: 'SOLVING_ACTIVE',
    NotSolving: 'NOT_SOLVING'
} as const;
export type SolverStatus = typeof SolverStatus[keyof typeof SolverStatus];


export function instanceOfSolverStatus(value: any): boolean {
    for (const key in SolverStatus) {
        if (Object.prototype.hasOwnProperty.call(SolverStatus, key)) {
            if (SolverStatus[key as keyof typeof SolverStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SolverStatusFromJSON(json: any): SolverStatus {
    return SolverStatusFromJSONTyped(json, false);
}

export function SolverStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolverStatus {
    return json as SolverStatus;
}

export function SolverStatusToJSON(value?: SolverStatus | null): any {
    return value as any;
}

export function SolverStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): SolverStatus {
    return value as SolverStatus;
}

