/* tslint:disable */
/* eslint-disable */
/**
 * dicoop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Settings } from './Settings';
import {
    SettingsFromJSON,
    SettingsFromJSONTyped,
    SettingsToJSON,
    SettingsToJSONTyped,
} from './Settings';

/**
 * 
 * @export
 * @interface TimeSlot
 */
export interface TimeSlot {
    /**
     * 
     * @type {string}
     * @memberof TimeSlot
     */
    name?: string;
    /**
     * 
     * @type {Settings}
     * @memberof TimeSlot
     */
    settings?: Settings;
}

/**
 * Check if a given object implements the TimeSlot interface.
 */
export function instanceOfTimeSlot(value: object): value is TimeSlot {
    return true;
}

export function TimeSlotFromJSON(json: any): TimeSlot {
    return TimeSlotFromJSONTyped(json, false);
}

export function TimeSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlot {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'settings': json['settings'] == null ? undefined : SettingsFromJSON(json['settings']),
    };
}

export function TimeSlotToJSON(json: any): TimeSlot {
    return TimeSlotToJSONTyped(json, false);
}

export function TimeSlotToJSONTyped(value?: TimeSlot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'settings': SettingsToJSON(value['settings']),
    };
}

